name: EPICS building

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install the packages
      run: |
        sudo apt update
        sudo apt install -y linux-headers-$(uname -r) build-essential coreutils ipmitool libtool automake  tree re2c darcs 
        sudo apt install -y libreadline-dev libxt-dev x11proto-print-dev libxmu-headers libxmu-dev libxpm-dev libxmuu-dev libxmuu1 libpcre++-dev python-dev libnetcdf-dev libhdf5-dev libpng-dev libbz2-dev libxml2-dev libusb-dev libusb-1.0-0-dev libudev-dev libsnmp-dev libraw1394-dev libboost-dev libboost-regex-dev libboost-filesystem-dev libopencv-dev
        sudo apt install -y libtirpc-dev  libblosc-dev libtiff-dev
    - uses: actions/checkout@v1
    - name: Setup repo
      run: |
        mkdir -p ~/bin
        export PATH=~/bin:$PATH
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
    - name: Download the manifest
      run: | 
        mkdir epics_env
        cd epics_env
        ~/bin/repo init -u https://github.com/jeonghanlee/epics_manifest.git
        ~/bin/repo sync --no-clone-bundle
        make init
        make base
        make modules
